version: '3.6'
services:
  kafka:
    container_name: kafka-container
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://<ip-address>:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    image: 'bitnami/kafka:latest'
    logging:
      options:
        max-size: "1m"
        max-file: "2"
    networks:
      - <network-name>-network
    ports:
      - '9092:9092'

  mongodb:
    build: 
      context: ./mongodb
    container_name: mongo-container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=<username>
      - MONGO_INITDB_ROOT_PASSWORD=<password>
    image: 'mongodb'
    ports:
      - '27017:27017'
    volumes:
      - mongodb-cache:/data/db
      - ./mongodb/mongod.conf:/etc/mongod.conf

  zookeeper:
    container_name: zookeeper-container
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    image: 'bitnami/zookeeper:latest'
    logging:
      options:
        max-size: "1m"
        max-file: "2"
    networks:
      - <network-name>-network
    ports:
      - '2181:2181'
networks:
  <network-name>-network:
    driver: bridge
volumes:
  mongodb-cache: